### PR TITLE
Update the code build deployment to auto update the latest task definition

### PR DESCRIPTION
**Pull request by ahobson**
## Description

Use the AWS CLI + jq to get the latest task definition so the deployment knows which one to update

### CODE REVIEW

**Comment by duncan-truss** [comment]
@ahobson Should `jq` be added to the requirements-dev.txt or Brewfile.local?  I don't have nix setup yet.  The codebuild logs looked successful though
Screen Shot 2021-11-05 at 4 56 09 PM
h

**Comment by ahobson** [comment]
> @ahobson Should `jq` be added to the requirements-dev.txt or Brewfile.local? I don't have nix setup yet. The codebuild logs looked successful though

@duncan-truss so ... I had to look this up myself.

This is running in aws code build with the aws image which has a *bunch* of stuff installed, including jq. I found what's in the image here:

https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile

**Comment by duncan-truss** [comment]
> > @ahobson Should `jq` be added to the requirements-dev.txt or Brewfile.local? I don't have nix setup yet. The codebuild logs looked successful though
> 
> @duncan-truss so ... I had to look this up myself.
> 
> This is running in aws code build with the aws image which has a _bunch_ of stuff installed, including jq. I found what's in the image here:
> 
> https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile

That's right we wouldn't care if it was installed locally unless you wanted to test, so it doesn't need to be in the nix dependencies either?

**Review by duncan-truss — APPROVED** [review]

**Comment by ahobson** [comment]
> > > @ahobson Should `jq` be added to the requirements-dev.txt or Brewfile.local? I don't have nix setup yet. The codebuild logs looked successful though
> > 
> > 
> > @duncan-truss so ... I had to look this up myself.
> > This is running in aws code build with the aws image which has a _bunch_ of stuff installed, including jq. I found what's in the image here:
> > https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile
> 
> That's right we wouldn't care if it was installed locally unless you wanted to test, so it doesn't need to be in the nix dependencies either?

Yeah, I put it in the nix dependencies so if someone did want to debug/try locally, it would work for them (and me)

**Pull request merged**
